export { default as $padding } from '@styled/variants/padding'
export { default as $margin } from '@styled/variants/margin'
export { default as $corners } from '@styled/variants/radius'
export { default as $borders } from '@styled/variants/border'
export { default as $shadow } from '@styled/variants/shadow'
export { default as $fill } from '@styled/variants/fill'
export { default as $borderfill } from '@styled/variants/borderfill'
export { default as $textfill } from '@styled/variants/textfill'
